name: lawyer
description: A Flutter package to set and obey the rules.
version: 0.1.0
homepage: https://github.com/envererdem18/lawyer
repository: https://github.com/envererdem18/lawyer


environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
